/**
 * In-App Notification System Type Definitions
 *
 * Type definitions for the unified notification system including
 * broadcasts, user notifications, templates, and preferences.
 *
 * Architecture:
 * - Broadcasts: Stored in shared-features Firebase (zaions_broadcasts)
 * - User notifications: Stored in consumer project's Firebase
 * - Templates: Stored in shared-features Firebase (zaions_notification_templates)
 *
 * @author Ahsan Mahmood <aoneahsan@gmail.com>
 */

import { Timestamp } from 'firebase/firestore';

// ============================================================================
// NOTIFICATION CATEGORIES & TYPES
// ============================================================================

/**
 * Standard notification categories for grouping and filtering
 */
export type NotificationCategory =
  | 'system' // Maintenance, updates, outages
  | 'account' // Welcome, security, profile changes
  | 'activity' // CRUD operations, user actions
  | 'report' // Weekly/monthly summaries
  | 'promotional' // Tips, features, holidays
  | 'social'; // Shares, mentions, comments

/**
 * Visual notification type for styling
 */
export type NotificationType =
  | 'info' // General information
  | 'success' // Positive feedback
  | 'warning' // Attention needed
  | 'error' // Something went wrong
  | 'reminder' // Time-based reminder
  | 'milestone' // Achievement/progress
  | 'announcement'; // Important announcement

/**
 * Priority levels for notifications
 */
export type NotificationPriority = 'urgent' | 'high' | 'normal' | 'low';

/**
 * Source of the notification
 */
export type NotificationSource =
  | 'system' // Auto-generated by system
  | 'event' // Triggered by user action
  | 'broadcast' // Cross-project announcement
  | 'admin'; // Sent by admin

/**
 * Broadcast display variants
 */
export type BroadcastVariant = 'banner' | 'modal' | 'toast' | 'bell';

/**
 * Broadcast status
 */
export type BroadcastStatus = 'draft' | 'scheduled' | 'active' | 'ended';

/**
 * Target platforms for notifications
 */
export type NotificationPlatform = 'web' | 'android' | 'ios';

/**
 * Target audience for broadcasts
 */
export type NotificationAudience = 'all' | 'authenticated' | 'anonymous';

// ============================================================================
// STANDARD EVENT TYPES
// ============================================================================

/**
 * Standard event types that trigger notifications
 */
export type StandardEventType =
  // Account Events
  | 'ACCOUNT_CREATED'
  | 'ACCOUNT_WELCOME'
  | 'NEW_DEVICE_SIGNIN'
  | 'PASSWORD_CHANGED'
  | 'PROFILE_UPDATED'
  | 'ACCOUNT_DELETED'
  // Report Events
  | 'DAILY_SUMMARY'
  | 'WEEKLY_SUMMARY'
  | 'MONTHLY_SUMMARY'
  | 'QUARTERLY_SUMMARY'
  | 'YEARLY_SUMMARY'
  // Promotional Events
  | 'APP_TIP'
  | 'HIDDEN_FEATURE'
  | 'NEW_FEATURE_ANNOUNCEMENT'
  | 'HOLIDAY_GREETING'
  // System Events
  | 'SYSTEM_MAINTENANCE'
  | 'APP_UPDATE_AVAILABLE'
  | 'DATA_EXPORT_READY'
  // Activity Events (Generic CRUD)
  | 'ITEM_CREATED'
  | 'ITEM_UPDATED'
  | 'ITEM_DELETED'
  | 'BULK_OPERATION_COMPLETE';

// ============================================================================
// BASE NOTIFICATION INTERFACE
// ============================================================================

/**
 * Base notification fields shared across all notification types
 */
export interface BaseNotification {
  /** Unique notification ID */
  id: string;
  /** Notification title */
  title: string;
  /** Notification message/body */
  message: string;
  /** Visual type for styling */
  type: NotificationType;
  /** Category for grouping/filtering */
  category: NotificationCategory;
  /** Whether the notification has been read */
  isRead: boolean;
  /** Whether this notification is important/pinned */
  isImportant?: boolean;
  /** Optional action URL to navigate to */
  actionUrl?: string;
  /** Optional action button text */
  actionText?: string;
  /** When the notification was created */
  createdAt: Date | Timestamp;
  /** When the notification was read */
  readAt?: Date | Timestamp;
  /** Additional metadata for custom use */
  metadata?: Record<string, unknown>;
}

// ============================================================================
// USER NOTIFICATION
// ============================================================================

/**
 * User-specific notification stored in consumer project's Firebase
 * Collection: {prefix}_notifications/{notificationId}
 */
export interface UserNotification extends BaseNotification {
  /** User ID this notification belongs to */
  userId: string;
  /** How the notification was generated */
  source: NotificationSource;
  /** Reference to source entity (broadcast ID, event ID, etc.) */
  sourceId?: string;
  /** Event type if triggered by event */
  eventType?: StandardEventType | string;
  /** When the notification expires (auto-delete) */
  expiresAt?: Date | Timestamp;
}

/**
 * Input for creating a user notification
 */
export interface CreateUserNotificationInput {
  userId: string;
  title: string;
  message: string;
  type: NotificationType;
  category: NotificationCategory;
  source: NotificationSource;
  sourceId?: string;
  eventType?: StandardEventType | string;
  isImportant?: boolean;
  actionUrl?: string;
  actionText?: string;
  expiresAt?: Date;
  metadata?: Record<string, unknown>;
}

// ============================================================================
// BROADCAST NOTIFICATION
// ============================================================================

/**
 * Cross-project broadcast notification stored in shared-features Firebase
 * Collection: zaions_broadcasts/{broadcastId}
 */
export interface BroadcastNotification extends BaseNotification {
  /** Target project IDs (empty = all projects) */
  targetProjects: string[];
  /** Target platforms */
  targetPlatforms: NotificationPlatform[];
  /** Target audience */
  targetAudience: NotificationAudience;
  /** Broadcast status */
  status: BroadcastStatus;
  /** When the broadcast becomes active */
  startDate: Date | Timestamp;
  /** When the broadcast ends (null = no end) */
  endDate?: Date | Timestamp | null;
  /** Display priority (1-100, higher = more important) */
  priority: number;
  /** Whether user can dismiss this broadcast */
  dismissible: boolean;
  /** How to display this broadcast */
  variant: BroadcastVariant;
  /** Total impressions count */
  impressions: number;
  /** Total clicks count */
  clicks: number;
  /** Admin user ID who created */
  createdBy: string;
  /** Admin user ID who last updated */
  updatedBy?: string;
}

/**
 * Input for creating a broadcast
 */
export interface CreateBroadcastInput {
  title: string;
  message: string;
  type: NotificationType;
  category: NotificationCategory;
  targetProjects: string[];
  targetPlatforms: NotificationPlatform[];
  targetAudience: NotificationAudience;
  startDate: Date;
  endDate?: Date | null;
  priority: number;
  dismissible: boolean;
  variant: BroadcastVariant;
  isImportant?: boolean;
  actionUrl?: string;
  actionText?: string;
  metadata?: Record<string, unknown>;
}

/**
 * Input for updating a broadcast
 */
export interface UpdateBroadcastInput extends Partial<CreateBroadcastInput> {
  id: string;
  status?: BroadcastStatus;
}

// ============================================================================
// NOTIFICATION TEMPLATE
// ============================================================================

/**
 * Notification template for standard events
 * Collection: zaions_notification_templates/{templateId}
 */
export interface NotificationTemplate {
  /** Template ID */
  id: string;
  /** Template name for admin reference */
  name: string;
  /** Event type this template is for */
  eventType: StandardEventType | string;
  /** Notification category */
  category: NotificationCategory;
  /** Title with placeholders: "Welcome to {{appName}}, {{userName}}!" */
  title: string;
  /** Message with placeholders */
  message: string;
  /** List of variable names used in title/message */
  variables: string[];
  /** Visual notification type */
  type: NotificationType;
  /** Whether notifications from this template are important */
  isImportant: boolean;
  /** Default action URL (can use placeholders) */
  actionUrl?: string;
  /** Default action button text */
  actionText?: string;
  /** Whether this template is enabled */
  enabled: boolean;
  /** When template was created */
  createdAt: Date | Timestamp;
  /** When template was last updated */
  updatedAt: Date | Timestamp;
}

/**
 * Input for creating a template
 */
export interface CreateTemplateInput {
  name: string;
  eventType: StandardEventType | string;
  category: NotificationCategory;
  title: string;
  message: string;
  variables: string[];
  type: NotificationType;
  isImportant: boolean;
  actionUrl?: string;
  actionText?: string;
  enabled: boolean;
}

// ============================================================================
// USER NOTIFICATION PREFERENCES
// ============================================================================

/**
 * Category preference settings
 */
export interface CategoryPreference {
  /** Show in-app notifications for this category */
  inApp: boolean;
  /** Send push notifications for this category */
  push: boolean;
  /** Send email notifications for this category */
  email: boolean;
}

/**
 * Quiet hours configuration
 */
export interface QuietHoursConfig {
  /** Whether quiet hours are enabled */
  enabled: boolean;
  /** Start time in 24h format: "22:00" */
  start: string;
  /** End time in 24h format: "08:00" */
  end: string;
  /** User's timezone (IANA format) */
  timezone: string;
}

/**
 * Email digest configuration
 */
export interface EmailDigestConfig {
  /** Whether email digest is enabled */
  enabled: boolean;
  /** Digest frequency */
  frequency: 'daily' | 'weekly' | 'none';
}

/**
 * Push notification configuration
 */
export interface PushConfig {
  /** Whether push is enabled */
  enabled: boolean;
  /** OneSignal player ID */
  playerId?: string;
  /** Web push subscription */
  webPushSubscription?: PushSubscription;
}

/**
 * User notification preferences
 * Collection: {prefix}_notification_preferences/{userId}
 */
export interface NotificationPreferences {
  /** User ID */
  userId: string;
  /** Category-specific preferences */
  categories: Record<NotificationCategory, CategoryPreference>;
  /** Quiet hours settings */
  quietHours: QuietHoursConfig;
  /** Email digest settings */
  emailDigest: EmailDigestConfig;
  /** Push notification settings */
  push: PushConfig;
  /** When preferences were last updated */
  updatedAt: Date | Timestamp;
}

/**
 * Default notification preferences
 */
export const DEFAULT_NOTIFICATION_PREFERENCES: Omit<
  NotificationPreferences,
  'userId' | 'updatedAt'
> = {
  categories: {
    system: { inApp: true, push: true, email: false },
    account: { inApp: true, push: true, email: true },
    activity: { inApp: true, push: false, email: false },
    report: { inApp: true, push: false, email: true },
    promotional: { inApp: true, push: false, email: false },
    social: { inApp: true, push: true, email: false },
  },
  quietHours: {
    enabled: false,
    start: '22:00',
    end: '08:00',
    timezone: 'UTC',
  },
  emailDigest: {
    enabled: false,
    frequency: 'none',
  },
  push: {
    enabled: false,
  },
};

// ============================================================================
// NOTIFICATION EVENTS
// ============================================================================

/**
 * Event definition for triggering notifications
 */
export interface NotificationEventDefinition {
  /** Event type identifier */
  type: StandardEventType | string;
  /** Event display name */
  name: string;
  /** Event description */
  description: string;
  /** Default notification category */
  category: NotificationCategory;
  /** Default notification type */
  notificationType: NotificationType;
  /** Default priority */
  priority: NotificationPriority;
  /** Available template variables */
  variables: string[];
  /** Whether this event is enabled by default */
  defaultEnabled: boolean;
}

/**
 * Event trigger payload
 */
export interface NotificationEventPayload {
  /** Event type */
  type: StandardEventType | string;
  /** User ID to notify */
  userId: string;
  /** Variable values for template interpolation */
  data: Record<string, string | number | boolean>;
  /** Optional override for notification title */
  titleOverride?: string;
  /** Optional override for notification message */
  messageOverride?: string;
  /** Optional action URL */
  actionUrl?: string;
  /** Optional action text */
  actionText?: string;
  /** Additional metadata */
  metadata?: Record<string, unknown>;
}

// ============================================================================
// ANALYTICS TYPES
// ============================================================================

/**
 * Broadcast analytics summary
 */
export interface BroadcastAnalytics {
  broadcastId: string;
  title: string;
  status: BroadcastStatus;
  impressions: number;
  clicks: number;
  dismissals: number;
  ctr: number;
  byPlatform: Record<NotificationPlatform, { impressions: number; clicks: number }>;
  byProject: Record<string, { impressions: number; clicks: number }>;
  byDate: Array<{
    date: string;
    impressions: number;
    clicks: number;
  }>;
}

/**
 * Overall notification analytics
 */
export interface NotificationAnalytics {
  /** Total notifications sent */
  totalSent: number;
  /** Total notifications read */
  totalRead: number;
  /** Total notifications clicked */
  totalClicked: number;
  /** Read rate (read/sent) */
  readRate: number;
  /** Click rate (clicked/sent) */
  clickRate: number;
  /** Breakdown by category */
  byCategory: Record<
    NotificationCategory,
    {
      sent: number;
      read: number;
      clicked: number;
    }
  >;
  /** Breakdown by type */
  byType: Record<
    NotificationType,
    {
      sent: number;
      read: number;
      clicked: number;
    }
  >;
  /** Daily breakdown */
  byDate: Array<{
    date: string;
    sent: number;
    read: number;
    clicked: number;
  }>;
}

// ============================================================================
// COMPONENT PROPS
// ============================================================================

/**
 * Props for NotificationBell component
 */
export interface NotificationBellProps {
  /** Additional CSS classes */
  className?: string;
  /** Icon size in pixels */
  size?: number;
  /** Show count badge even when 0 */
  showZeroBadge?: boolean;
  /** Custom onClick handler (default: toggle panel) */
  onClick?: () => void;
}

/**
 * Props for NotificationPanel component
 */
export interface NotificationPanelProps {
  /** Whether the panel is open */
  isOpen: boolean;
  /** Called when panel should close */
  onClose: () => void;
  /** Maximum height for the panel */
  maxHeight?: string;
  /** Whether to show the filter tabs */
  showFilters?: boolean;
  /** Custom empty state component */
  emptyStateComponent?: React.ReactNode;
}

/**
 * Props for NotificationCard component
 */
export interface NotificationCardProps {
  /** The notification to display */
  notification: UserNotification;
  /** Called when notification is clicked */
  onClick?: () => void;
  /** Called when delete button is clicked */
  onDelete?: () => void;
  /** Whether to show delete button */
  showDelete?: boolean;
  /** Whether to show timestamp */
  showTimestamp?: boolean;
}

/**
 * Props for BroadcastBanner component
 */
export interface BroadcastBannerProps {
  /** The broadcast to display */
  broadcast: BroadcastNotification;
  /** Called when CTA is clicked */
  onActionClick?: () => void;
  /** Called when banner is dismissed */
  onDismiss?: () => void;
  /** Additional CSS classes */
  className?: string;
}

/**
 * Props for AnnouncementModal component
 */
export interface AnnouncementModalProps {
  /** The broadcast to display */
  broadcast: BroadcastNotification;
  /** Whether the modal is open */
  isOpen: boolean;
  /** Called when modal should close */
  onClose: () => void;
  /** Called when CTA is clicked */
  onActionClick?: () => void;
}

/**
 * Props for NotificationPreferences component
 */
export interface NotificationPreferencesProps {
  /** Current preferences */
  preferences: NotificationPreferences;
  /** Called when preferences change */
  onPreferencesChange: (preferences: NotificationPreferences) => void;
  /** Whether saving is in progress */
  isSaving?: boolean;
  /** Categories to show (default: all) */
  visibleCategories?: NotificationCategory[];
  /** Whether to show push settings */
  showPushSettings?: boolean;
  /** Whether to show email settings */
  showEmailSettings?: boolean;
  /** Whether to show quiet hours settings */
  showQuietHours?: boolean;
}

// ============================================================================
// HOOK RETURN TYPES
// ============================================================================

/**
 * Return type for useNotifications hook
 */
export interface UseNotificationsReturn {
  /** List of notifications */
  notifications: UserNotification[];
  /** Number of unread notifications */
  unreadCount: number;
  /** Whether notifications are loading */
  isLoading: boolean;
  /** Error if any */
  error: Error | null;
  /** Mark a notification as read */
  markAsRead: (notificationId: string) => Promise<void>;
  /** Mark all notifications as read */
  markAllAsRead: () => Promise<void>;
  /** Delete a notification */
  deleteNotification: (notificationId: string) => Promise<void>;
  /** Clear all notifications */
  clearAll: () => Promise<void>;
  /** Refresh notifications */
  refresh: () => Promise<void>;
}

/**
 * Return type for useBroadcasts hook
 */
export interface UseBroadcastsReturn {
  /** List of active broadcasts */
  broadcasts: BroadcastNotification[];
  /** Whether broadcasts are loading */
  isLoading: boolean;
  /** Error if any */
  error: Error | null;
  /** Dismiss a broadcast */
  dismissBroadcast: (broadcastId: string) => void;
  /** Track broadcast impression */
  trackImpression: (broadcastId: string) => void;
  /** Track broadcast click */
  trackClick: (broadcastId: string) => void;
  /** Check if broadcast was dismissed */
  isDismissed: (broadcastId: string) => boolean;
  /** Refresh broadcasts from cache */
  refresh: () => Promise<void>;
}

/**
 * Return type for useNotificationEvents hook
 */
export interface UseNotificationEventsReturn {
  /** Trigger a notification event */
  trigger: (payload: NotificationEventPayload) => Promise<void>;
  /** Trigger account created event */
  triggerAccountCreated: (data: { userName: string; email: string }) => Promise<void>;
  /** Trigger new device signin event */
  triggerNewDeviceSignin: (data: { deviceName: string; location?: string }) => Promise<void>;
  /** Trigger password changed event */
  triggerPasswordChanged: () => Promise<void>;
  /** Trigger profile updated event */
  triggerProfileUpdated: (data: { changes: string[] }) => Promise<void>;
  /** Trigger CRUD event */
  triggerCrudEvent: (data: {
    action: 'created' | 'updated' | 'deleted';
    entityType: string;
    entityName: string;
  }) => Promise<void>;
  /** Trigger app tip event */
  triggerAppTip: (data: { tipId: string; title: string; body: string }) => Promise<void>;
}

// ============================================================================
// SERVICE TYPES
// ============================================================================

/**
 * Options for fetching broadcasts
 */
export interface FetchBroadcastsOptions {
  /** Filter by project ID */
  projectId?: string;
  /** Filter by platform */
  platform?: NotificationPlatform;
  /** Filter by variant */
  variant?: BroadcastVariant;
  /** Filter by status */
  status?: BroadcastStatus;
  /** Maximum results */
  limit?: number;
}

/**
 * Options for fetching user notifications
 */
export interface FetchNotificationsOptions {
  /** User ID */
  userId: string;
  /** Filter by category */
  category?: NotificationCategory;
  /** Filter by read status */
  isRead?: boolean;
  /** Maximum results */
  limit?: number;
  /** Offset for pagination */
  offset?: number;
  /** Start date filter */
  startDate?: Date;
  /** End date filter */
  endDate?: Date;
}

// ============================================================================
// COLLECTION NAMES
// ============================================================================

/**
 * Shared collections (stored in shared-features Firebase)
 */
export const NOTIFICATION_COLLECTIONS = {
  /** Cross-project broadcasts */
  BROADCASTS: 'zaions_broadcasts',
  /** Notification templates */
  TEMPLATES: 'zaions_notification_templates',
  /** Broadcast events/analytics */
  BROADCAST_EVENTS: 'zaions_broadcast_events',
} as const;

/**
 * Get consumer project collection names
 * @param prefix - Project prefix (e.g., 'pp' for pregnancy-pal)
 */
export const getNotificationCollections = (prefix: string) =>
  ({
    /** User notifications */
    NOTIFICATIONS: `${prefix}_notifications`,
    /** User notification preferences */
    PREFERENCES: `${prefix}_notification_preferences`,
    /** Push subscriptions */
    PUSH_SUBSCRIPTIONS: `${prefix}_push_subscriptions`,
  }) as const;

// ============================================================================
// DISPLAY NAMES & CONSTANTS
// ============================================================================

/**
 * Category display names
 */
export const CATEGORY_NAMES: Record<NotificationCategory, string> = {
  system: 'System',
  account: 'Account',
  activity: 'Activity',
  report: 'Reports',
  promotional: 'Tips & Updates',
  social: 'Social',
};

/**
 * Category descriptions
 */
export const CATEGORY_DESCRIPTIONS: Record<NotificationCategory, string> = {
  system: 'Maintenance updates, outages, and system alerts',
  account: 'Welcome messages, security alerts, and profile changes',
  activity: 'Updates about your actions and changes',
  report: 'Weekly and monthly summaries of your activity',
  promotional: 'Tips, new features, and holiday greetings',
  social: 'Mentions, shares, and comments from others',
};

/**
 * Notification type display names
 */
export const TYPE_NAMES: Record<NotificationType, string> = {
  info: 'Information',
  success: 'Success',
  warning: 'Warning',
  error: 'Error',
  reminder: 'Reminder',
  milestone: 'Milestone',
  announcement: 'Announcement',
};

/**
 * Priority display names
 */
export const PRIORITY_NAMES: Record<NotificationPriority, string> = {
  urgent: 'Urgent',
  high: 'High',
  normal: 'Normal',
  low: 'Low',
};

/**
 * Event type display names
 */
export const EVENT_TYPE_NAMES: Record<StandardEventType, string> = {
  ACCOUNT_CREATED: 'Account Created',
  ACCOUNT_WELCOME: 'Welcome Message',
  NEW_DEVICE_SIGNIN: 'New Device Sign-in',
  PASSWORD_CHANGED: 'Password Changed',
  PROFILE_UPDATED: 'Profile Updated',
  ACCOUNT_DELETED: 'Account Deleted',
  DAILY_SUMMARY: 'Daily Summary',
  WEEKLY_SUMMARY: 'Weekly Summary',
  MONTHLY_SUMMARY: 'Monthly Summary',
  QUARTERLY_SUMMARY: 'Quarterly Summary',
  YEARLY_SUMMARY: 'Yearly Summary',
  APP_TIP: 'App Tip',
  HIDDEN_FEATURE: 'Hidden Feature',
  NEW_FEATURE_ANNOUNCEMENT: 'New Feature',
  HOLIDAY_GREETING: 'Holiday Greeting',
  SYSTEM_MAINTENANCE: 'System Maintenance',
  APP_UPDATE_AVAILABLE: 'App Update Available',
  DATA_EXPORT_READY: 'Data Export Ready',
  ITEM_CREATED: 'Item Created',
  ITEM_UPDATED: 'Item Updated',
  ITEM_DELETED: 'Item Deleted',
  BULK_OPERATION_COMPLETE: 'Bulk Operation Complete',
};

/**
 * Default broadcast priority
 */
export const DEFAULT_BROADCAST_PRIORITY = 50;

/**
 * Maximum notification title length
 */
export const MAX_NOTIFICATION_TITLE_LENGTH = 100;

/**
 * Maximum notification message length
 */
export const MAX_NOTIFICATION_MESSAGE_LENGTH = 500;
